"""empty message

Revision ID: 27c989070f01
Revises: ae6e9b536d51
Create Date: 2019-06-03 19:53:26.112317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c989070f01'
down_revision = 'ae6e9b536d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_update_time', table_name='posts')
    op.add_column('users', sa.Column('token_create', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_create')
    op.create_index('ix_posts_update_time', 'posts', ['update_time'], unique=False)
    # ### end Alembic commands ###
