"""empty message

Revision ID: 5e314a9bfac1
Revises: 7d2d6e5eff50
Create Date: 2019-06-26 20:21:34.205502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e314a9bfac1'
down_revision = '7d2d6e5eff50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('abstract', sa.Text(), nullable=True))
    op.add_column('tweets', sa.Column('abstract', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'abstract')
    op.drop_column('posts', 'abstract')
    # ### end Alembic commands ###
