"""empty message

Revision ID: d2a260f6c459
Revises: 60109cdbc7d5
Create Date: 2019-08-03 17:03:49.532485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2a260f6c459'
down_revision = '60109cdbc7d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_comments_created'), 'comments', ['created'], unique=False)
    op.drop_index('ix_comments_create_time', table_name='comments')
    op.drop_column('comments', 'create_time')
    op.add_column('me_follow_you', sa.Column('created', sa.DateTime(), nullable=True))
    op.drop_column('me_follow_you', 'create_time')
    op.add_column('messages', sa.Column('created', sa.DateTime(), nullable=True))
    op.drop_column('messages', 'create_time')
    op.add_column('notifications', sa.Column('created', sa.DateTime(), nullable=True))
    op.drop_column('notifications', 'create_time')
    op.add_column('posts', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('updated', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_created'), 'posts', ['created'], unique=False)
    op.drop_index('ix_posts_create_time', table_name='posts')
    op.drop_column('posts', 'update_time')
    op.drop_column('posts', 'create_time')
    op.add_column('tweets', sa.Column('created', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tweets_created'), 'tweets', ['created'], unique=False)
    op.drop_index('ix_tweets_create_time', table_name='tweets')
    op.drop_column('tweets', 'create_time')
    op.add_column('user_collect_post', sa.Column('created', sa.DateTime(), nullable=True))
    op.drop_column('user_collect_post', 'create_time')
    op.add_column('user_collect_tweet', sa.Column('created', sa.DateTime(), nullable=True))
    op.drop_column('user_collect_tweet', 'create_time')
    op.add_column('user_like_comment', sa.Column('created', sa.DateTime(), nullable=True))
    op.drop_column('user_like_comment', 'create_time')
    op.add_column('user_like_post', sa.Column('created', sa.DateTime(), nullable=True))
    op.drop_column('user_like_post', 'create_time')
    op.add_column('user_like_tweet', sa.Column('created', sa.DateTime(), nullable=True))
    op.drop_column('user_like_tweet', 'create_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_like_tweet', sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user_like_tweet', 'created')
    op.add_column('user_like_post', sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user_like_post', 'created')
    op.add_column('user_like_comment', sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user_like_comment', 'created')
    op.add_column('user_collect_tweet', sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user_collect_tweet', 'created')
    op.add_column('user_collect_post', sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user_collect_post', 'created')
    op.add_column('tweets', sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_tweets_create_time', 'tweets', ['create_time'], unique=False)
    op.drop_index(op.f('ix_tweets_created'), table_name='tweets')
    op.drop_column('tweets', 'created')
    op.add_column('posts', sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('update_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_posts_create_time', 'posts', ['create_time'], unique=False)
    op.drop_index(op.f('ix_posts_created'), table_name='posts')
    op.drop_column('posts', 'updated')
    op.drop_column('posts', 'created')
    op.add_column('notifications', sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('notifications', 'created')
    op.add_column('messages', sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'created')
    op.add_column('me_follow_you', sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('me_follow_you', 'created')
    op.add_column('comments', sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_comments_create_time', 'comments', ['create_time'], unique=False)
    op.drop_index(op.f('ix_comments_created'), table_name='comments')
    op.drop_column('comments', 'created')
    # ### end Alembic commands ###
